# Generated by Django 3.1.4 on 2021-01-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210124_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_leaving',
            field=models.DateField(blank=True, default='9999-12-31'),
        ),
    ]
