# Generated by Django 3.1.4 on 2021-01-24 15:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210124_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='First_Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='Last_Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('MR', 'Married'), ('SN', 'Single'), ('DI', 'Divorced'), ('WI', 'Widowed')], max_length=15, verbose_name='Marital_Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone_Number'),
        ),
    ]
