# Generated by Django 3.1.4 on 2021-01-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50, unique=True, verbose_name='Department')),
                ('Is_Active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=15, verbose_name='Grade')),
                ('grade_description', models.CharField(max_length=60, verbose_name='Grade Description')),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_leaving',
            field=models.DateField(blank=True, default='9999-12-31', help_text='The Leaving Date determines whether it is an Active Employee', verbose_name='Date_of_Leaving'),
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('appraisal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_supervisor_comments', models.TextField()),
                ('appraisal_date', models.DateField(verbose_name='Appraisal_Year')),
                ('last_update', models.DateField(auto_now_add=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.rating')),
            ],
            options={
                'verbose_name_plural': 'Appraisals',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
            preserve_default=False,
        ),
    ]
