# Generated by Django 3.1.4 on 2021-01-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20210127_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mgr_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='lala', max_length=45, verbose_name='First_Name')),
                ('last_name', models.CharField(default='dineros', max_length=45, verbose_name='Last_Name')),
            ],
            options={
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.manager'),
        ),
    ]
