# Generated by Django 3.1.4 on 2021-01-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210128_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.manager'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='First_Name'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='Last_Name'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='mgr_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
