# Generated by Django 3.1.4 on 2021-01-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20210128_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee.manager'),
        ),
    ]
