# Generated by Django 3.1.4 on 2021-01-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20210128_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='emp_id',
            field=models.IntegerField(default=2),
        ),
    ]
