# Generated by Django 3.1.4 on 2021-01-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_manager_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='emp_id',
            field=models.IntegerField(),
        ),
    ]
