# Generated by Django 3.1.4 on 2021-01-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20210128_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Appraisal_Year'),
        ),
    ]
