# Generated by Django 3.1.4 on 2021-01-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_auto_20210129_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='rating_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.rating'),
        ),
    ]
